---
- name: AUTOMATIC BACK OF RUNNING-CONFIG
  hosts: juniper
  gather_facts: false
  connection: local

  vars: 
   ansible_user: "root" 
   ansible_password: "root20194"

  tasks:
   - name: run show version on remote devices
     junos_command:
       commands: "show interface terse"
     register: config
     
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/show_version_{{ inventory_hostname }}_{{ '%Y-%m-%d_%Hh-%Mm-%Ss' | strftime }}.txt"

...

