---
- name: AUTOMATIC BACK OF RUNNING-CONFIG
  hosts: juniper
  gather_facts: false
  connection: local

  vars: 
   ansible_user: "root" 
   ansible_password: "root20194"

  tasks:
   - name: run show version on remote devices
     junos_command:
       commands: show interfaces
     
   - name: SAVE OUTPUT TO ./backups/
     copy:
       content: "{{ config.stdout[0] }}"
       dest: "backups/show_port_{{ inventory_hostname }}_{{ '%Y-%m-%d_%Hh-%Mm-%Ss' | strftime }}.txt"

   - name: configure description on port
     junos_config:
       lines: /configure port 1/1/1 description "TO_US-WEST"
...

